package com.example.groupproject;
/**
 * This class represents Movie data object;
 * @author Weiping Guo
 * @version 1.0
 */
public class MovieData {
    /** This holds the text of the title of movie */
    String title;
    /** This holds the text of the year of movie */
    String year;
    /** This holds the text of the rating of movie */
    String rating;
    /** This holds the text of the runtime of movie */
    String runtime;
    /** This holds the text of the actor of movie */
    String actor;
    /** This holds the text of the plot of movie */
    String plot;
    /** This holds the text of the image url of movie */
    String imageURL;
    /** This holds the id of the movie autogenerated by the database */
    long id;

    /**
     * Constructor of a detailed movie
     * @param title the title of movie
     * @param year the year of movie
     * @param rating the rating of movie
     * @param runtime the runtime of movie
     * @param actors the actor of movie
     * @param plot the plot of movie
     * @param imageURL the image url of movie
     * @param id id of the movie autogenerated by the database
     */
    public MovieData(String title, String year, String rating, String runtime, String actors, String plot, String imageURL, long id){
        this.title = title;
        this.year = year;
        this.rating = rating;
        this.runtime = runtime;
        this.actor = actors;
        this.plot = plot;
        this.imageURL = imageURL;
        setId(id);
    }

    public void setId(long l){
        id = l;
    }

    public long getId(){
        return id;
    }

    public String getTitle() {
        return title;
    }

    public String getYear() {
        return year;
    }

    public String getRating() {
        return rating;
    }

    public String getRuntime() { return runtime; }

    public String getActor() {
        return actor;
    }

    public String getPlot() {
        return plot;
    }

    public String getImageURL() {
        return imageURL;
    }
    /**
     * Constructor of a detailed movie without id
     * @param title the title of movie
     * @param year the year of movie
     * @param rating the rating of movie
     * @param runtime the runtime of movie
     * @param actors the actor of movie
     * @param plot the plot of movie
     * @param imageURL the image url of movie
     */
    public MovieData(String title, String year, String rating, String runtime, String actors, String plot, String imageURL) {
        this.title = title;
        this.year = year;
        this.rating = rating;
        this.runtime = runtime;
        this.actor = actors;
        this.plot = plot;
        this.imageURL = imageURL;
    }
}
